name = "telehub-image-compressor"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[limits]
cpu_ms = 30000

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "telehub-compressed-images"

[triggers]
crons = ["0 * * * *"]
