name = "telehub-image-compressor"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[kv_namespaces]]
binding = "IMAGE_KV"
id = "86ec4a4f64c54d53bb65369ad602a166"

[triggers]
crons = ["0 * * * *"]
